import express from 'express';
import walletController from '../controllers/walletController';
import { protect } from '../middleware/auth.middleware';
const router = express.Router();
router.get('/deposit-history', protect, walletController.getDepositHistory);
router.get('/transactions', protect, walletController.getWalletTransactions);
router.get('/filter', protect, walletController.filterTransactions);
router.get('/export', protect, walletController.exportTransactions);
router.get('/currency', protect, walletController.getWalletCurrency);
router.get('/balance', protect, walletController.getWalletBalance);
router.post('/transfer', protect, walletController.transferToUser);
router.post('/withdraw', protect, walletController.requestWithdrawal);
router.post('/credit', protect, walletController.creditWallet);
router.post('/lock/:id', protect, walletController.lockWallet);
router.post('/unlock/:id', protect, walletController.unlockWallet);
export default router;
